name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Bot on SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd /home/ubuntu/BotPapa/
            git reset --hard
            git clean -fd
            git pull origin master
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S npm install
            pm2 restart Bot